### ISSUE TITLE
Expand the "DDL" acronym

### ISSUE THREAD

**Issue by shlomif** [iamalnewkirk/doodle#2]
I didn't know what it is. I tried doing it myself by editing https://github.com/iamalnewkirk/doodle/blob/master/lib/Doodle.pod but `dzil test --all` overwrote my changes. This is one reason why it is not advised to keep generated files in the source repo. Thanks!

**Comment by iamalnewkirk** [comment]
Hey @shlomif, long time. Thanks for commenting and trying to contribute. I disagree on keeping generated files in the repo, but I also acknowledge that the lack of a CONTRIBUTORS file will cause this kind of confusion. 

To your other point raised on IRC, the tests were running slow due to optimization issue in Data-Object, the underlying Moo-based development framework. Those issue have been fixed-ish. Optimizations were made and the test sweet runs much faster now!

Please let me know if you have any interest in contributing! I'll add a CONTRIBUTORS file shortly.

**Comment by shlomif** [comment]
@iamalnewkirk : thanks for the fixes! I still want to contribute.

**Comment by iamalnewkirk** [comment]
@shlomif See https://github.com/iamalnewkirk/doodle/blob/master/CONTRIBUTING.mkdn
